// <auto-generated />
namespace saasdemo.data.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSales));
        
        string IMigrationMetadata.Id
        {
            get { return "201802220549575_AddSales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
